Change the gcc compile switch to "-Wl,--allow-shlib-undefined"
Otherwise, the following errors are reported:
[  7%] Linking C shared library libesdm.so
/lib64/libpthread.so.0: undefined reference to `_dl_deallocate_tls@GLIBC_PRIVATE'
/lib64/libc.so.6: undefined reference to `_dl_argv@GLIBC_PRIVATE'
/lib64/libpthread.so.0: undefined reference to `_dl_allocate_tls@GLIBC_PRIVATE'
...
collect2: error: ld returned 1 exit status
make[2]: *** [libesdm.so] Error 1
make[1]: *** [CMakeFiles/esdm.dir/all] Error 2
make: *** [all] Error 2